name: symfony-3
recipe: lamp
config:
  webroot: ./sf/web
  php: '7.3'
  database: mysql:5.7

tooling:
  sf:
    service: appserver
    description: Run Symfony commands
    cmd: bin/console

services:
  appserver:
    type: php
    build_as_root:
      - docker-php-ext-install sockets
    xdebug: true
    config:
      php: .lando/php/php.ini
